- name: Gather facts about samba shares
  hosts: share
  gather_facts: yes

- name: Add php ppa and update apt
  hosts: cloud_share
  become: true
  tasks:
    - name: Add PHP ppa repo
      apt_repository:
        repo: ppa:ondrej/php
        state: present
    - name: Install additional packages
      apt:
        pkg:
          - php7.4-apcu # required for owncloud on ubuntu bionic
          - smbclient # required for smb storage backend

- name: Install owncloud-php
  hosts: cloud_share
  become: true
  vars:
    php_default_version: "7.4"
  roles:
    - owncloud-php

# owncloud-php messed up the installation so we have
# to remove all php8.1 files
- name: Deinstall php8.1 modules
  hosts: cloud_share
  become: true
  tasks:
      - name: remove php8.1
        shell: 
          cmd: apt remove -y $(dpkg --get-selections  | grep php8.1 | awk '{print $1}' | tr '\n' ' ')
      - name: fix php modules
        apt:
            pkg:
                - php7.4-apcu
                - php7.4-redis
                - php7.4-sqlite3

- name: Install owncloud and required services
  hosts: cloud_share
  become: true
  vars:
    php_default_version: "7.4"
  roles:
    - owncloud-mariadb
    - owncloud-redis
    - owncloud-apache
    - owncloud

- name: Prepare local files
  hosts: cloud_share
  become: true
  tasks:
    - name: Ensure destination directory exists
      file:
        path: "{{ owncloud_prepared_files_dest }}"
        state: directory
        owner: www-data
        group: root
    - name: Ensure directories exist
      file:
        path: "{{ owncloud_prepared_files_dest }}/{{ item.path }}"
        state: directory
        owner: www-data
        group: root
      with_filetree: "{{ owncloud_prepared_files_src }}"
      when: item.state == 'directory'
    - name: Copy additional files
      copy: 
        src: "{{ item.src }}" 
        dest: "{{ owncloud_prepared_files_dest }}/{{ item.path }}" 
        owner: www-data
        group: root
      with_filetree: "{{ owncloud_prepared_files_src }}"
      when: item.state == 'file'

- name: Prepare user, group and mount configuration
  hosts: cloud_share
  become: true
  roles:
    - ait.owncloud.config
        
