- name: Manage CA authority
  import_playbook: ./certificate_authority.yml
  tags: [ca]

- name: Manage OpenVPn server cert
  import_playbook: ./server_certificate.yml
  tags: [server]

- name: Gather facts about remote employees
  hosts: remote_employee
  gather_facts: yes
  tags: [certs]

- name: Manage user certificates
  hosts: localhost
  connection: local
  tasks:
    - name: Manage user certificates
      include_tasks: ./user_certificates.yml
      loop: "{{ groups['remote_employee'] }}"
      loop_control:
        loop_var: host
  tags: [certs]

- name: Configure OpenVPN on remote employees
  hosts: remote_employee
  become: yes
  roles:
    - openvpn-client
  tags: [openvpn, client]
      