
beats_version: 7.13.2

# output config for all beats

beats_username: "beats"
beats_password: "b3at5"

beats_output_conf:
  logstash:
    hosts: ["{{ hostvars['monitoring'].openstack.addresses.local[0].addr }}:5044"]

# ilm config
beats_ilm_policy_max_age: 1d
beats_ilm_policy_max_size: 25gb
beats_ilm_policy_delete: true
beats_ilm_policy_delete_min_age: 5d
