
# this is needed for some of the SM configs
- name: Gather facts about other hosts
  hosts: all
  gather_facts: yes

- name: Install and configure simulation state machines
  hosts: employee,ext_user
  roles:
    - kyoushi-simulation