# openstack inventory
plugin: openstack.cloud.openstack
expand_hostvars: no
fail_on_errors: yes
private: yes
strict: False
compose:
  #
  # References to `__this_does_not_exists__` are used to force ansible to not set the specific variable.
  # This needs to be done if you only want to define a variable in specific cases (e.g., only for employees)
  #

  # extracts the internal/remote employee index from the machine name
  employee_index:
          (openstack.name | regex_replace('(.*_employee_)(\d*)', '\2')) | int
          if openstack.name.startswith('internal_employee_') or openstack.name.startswith('remote_employee_')
          else __this_does_not_exists__
  ext_user_index:
          (openstack.name | regex_replace('(ext_user_)(\d*)', '\2')) | int
          if openstack.name.startswith('ext_user_') else __this_does_not_exists__
  