- name: Test playbook for debugging
  hosts: all
  gather_facts: yes

- name: Placeholder playbook
  hosts: inet-firewall
  tasks: 
    - debug:
            msg: "{{ hostvars['internal_share'].openstack.addresses }}"
  
