proxied_name: www
proxy_aliases: |
  [
    {% for host in groups['proxied'] %}
    {
      "proxy_host": "{{ host }}"
    }{% if not loop.last %},{% endif %}
    {% endfor %}
  ]

dns_domains: 
  - domain: company
    hostname: proxy
    aliases: "{{ proxy_aliases }}"
      