apache2_additional_packages: 
  - libxml2-dev

# modules needed for reverse proxy
apache2_modules:
  - name: proxy
  - name: proxy_ajp
  - name: proxy_http
  - name: rewrite
  - name: deflate
  - name: headers
  - name: ssl
  - name: proxy_connect
  - name: proxy_html
  - name: authz_host

apache2_proxy_vhosts: |
  [
    {% for host in groups['proxied'] %}
    {
      "name": "{{ hostvars[host].proxied_name }}.{{ domains.company_external.domain }}",
      "enabled": {{ hostvars[host].reverse_proxy_enabled | default(True) }},
      "proxy_target": "{{ hostvars[host].dns.dmz.fqdn }}",
      "vhost_template": "templates/reverse_vhost.conf.j2",
      "redirect_ssl": {{ hostvars[host].proxied_redirect_ssl | default(True) }},
      "cert": "{{ ca_servers_path }}/{{ inventory_hostname }}/{{ hostvars[host].proxied_name }}.{{ dns.company.domain }}/{{ hostvars[host].proxied_name }}.{{ dns.company.domain }}.crt",
      "key": "{{ ca_servers_path }}/{{ inventory_hostname }}/{{ hostvars[host].proxied_name }}.{{ dns.company.domain }}/{{ hostvars[host].proxied_name }}.{{ dns.company.domain }}.key",
      "copycerts": true
    }{% if not loop.last %},{% endif %}
    {% endfor %}
  ]

apache2_webserver_vhosts:
  # catch all vhost
  - name: 000-catch-all
    server_name: "{{ dns.company.fqdn }}"
    vhost_dir: false
    vhost_template: "templates/catch_all_vhost.conf.j2"
    "cert": "{{ ca_servers_path }}/{{ inventory_hostname }}/{{ dns.company.hostname }}.{{ dns.company.domain }}/{{ dns.company.hostname }}.{{ dns.company.domain }}.crt"
    "key": "{{ ca_servers_path }}/{{ inventory_hostname }}/{{ dns.company.hostname }}.{{ dns.company.domain }}/{{ dns.company.hostname }}.{{ dns.company.domain }}.key"
    "copycerts": true
  

apache2_vhosts: "{{ apache2_proxy_vhosts + apache2_webserver_vhosts }}"
    
