- name: Configure debiansnapshot for company mail server
  hosts: mail
  become: true
  roles:
    - debiansnapshot

- name: Configure mailservers
  hosts: exim
  become: true
  roles: 
    - exim
    - dovecot
    - grog.user
    - horde
    - clamav
