ext_user: "{{ ext_mail_users[ext_user_index] }}"

management_user_key: "{{ lookup('file', ait_ssh_key_pub) }}"

ext_user_account:
  name: "{{ ext_user.username }}"
  comment: "{{ ext_user.first_name }} {{ ext_user.last_name }}"
  shell: '/bin/bash'
  password: "{{ ext_user.password | password_hash('sha512', ext_user.password_salt) }}"
  authorized_keys:
    - key: "{{ management_user_key }}"
      exclusive: no
  sudo: "{{ ext_user.sudo | default({'hosts': 'ALL', 'as': 'ALL', 'commands': 'ALL', 'nopasswd': True}, True) }}"

user_extra_packages:
  - firefox
  - chromium-browser