ssh_keys_base_path: "{{ lookup('env','LOCAL_PACKAGE_ANSIBLE_PATH') }}/data/ssh-keys"
management_user_key: "{{ lookup('file', ait_ssh_key_pub) }}"

# combine user dicts into one for convenience
game_users: "{{ employees | combine(service_users) }}"