postfix_mynetworks: "127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 {{ ansible_default_ipv4['address'] }}/32"

# configures no login shell for all users
# (for admin users this is overridden via the shell dict field)
user_shell: "/usr/sbin/nologin"
user_list: |
  [
  {% for user in mail_users %}
  {# set name to email_user and hash password #}
  {% do user.update({'name': user.email_user, 'password': (user.password | password_hash('sha512', user.password_salt)) }) %}
  {{ user | to_json }}{% if not loop.last%},{% endif %}
  {% endfor %}
  ]

mailserver_cert_name: "{{ dns_hostname }}.{{ dns_domain }}"

## exim

exim_mailname: "{{ dns[dns_domain].fqdn }}"
exim_ip: "{{ ansible_default_ipv4.address }}"
exim_maildomain: "{{ domains[dns_domain].domain }}"
exim_domain: "{{ domains[dns_domain].domain }}"

## dovecot
dovecot_postfix_auth: yes
dovecot_ssl_cert_src: "{{ ca_servers_path }}/{{ inventory_hostname }}/{{ mailserver_cert_name }}/{{ mailserver_cert_name }}.crt"
dovecot_ssl_cert: /etc/dovecot/private/dovecot.pem

dovecot_ssl_key_src: "{{ ca_servers_path }}/{{ inventory_hostname }}/{{ mailserver_cert_name }}/{{ mailserver_cert_name }}.key"
dovecot_ssl_key: /etc/dovecot/private/dovecot.key

