- name: Start employee simulations
  hosts: attacker_0
  gather_facts: no
  tasks:
    - name: Clean SM log
      file:
        path: /var/log/kyoushi/{{ kyoushi_sm_name }}/sm.log
        state: absent
      become: yes
      when: kyoushi_sm_run_clean|default(False)

    - name: Start attacker SM
      service:
        name: "{{ kyoushi_sm_name }}.service"
        state: started
      become: yes
