- name: Start employee simulations
  hosts: attacker_0
  gather_facts: no
  tasks:
    - name: Clean SM log
      file:
        path: /var/log/kyoushi/{{ kyoushi_sm_name }}/sm.log
        state: absent
      become: yes
      when: kyoushi_sm_run_clean|default(False)

    - name: Start attacker SM
      shell: nohup {{ kyoushi_sm_name }} </dev/null >/dev/null 2>&1 &
      args:
        executable: /bin/bash
      become: yes
      become_user: "{{ kyoushi_user_name }}"