
- name: Fact gathering pre dns server conifguration
  hosts: all
  gather_facts: yes

- name: Update apt
  hosts: dnsservers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: [install]

    - name: Temporarly use upstream DNS server as main
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^nameserver\s+.*'
        line: nameserver {{ dns_bootstrap_upstream | default('8.8.8.8') }}
      become: yes

- name: Configure the dns servers
  hosts: dnsservers
  become: true
  roles:
      - dnsmasq
      - maradns
  tasks:
    - name: Re-configure to use system resolver
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^nameserver\s+.*'
        line: nameserver 127.0.0.53
      become: yes