employee_id: "{{ remote_employees[employee_index|int] }}"

employee_user:
  name: "{{ employee.username }}"
  comment: "{{ employee.first_name }} {{ employee.last_name }}"
  shell: '/bin/bash'
  password: "{{ employee.password | password_hash('sha512', employee.password_salt) }}"
  authorized_keys:
    - key: "{{ management_user_key }}"
      exclusive: no
  sudo: "{{ employee.sudo | default({'hosts': 'ALL', 'as': 'ALL', 'commands': 'ALL', 'nopasswd': True}, True) }}"