- name: Kill all user processes
  hosts: employee
  gather_facts: no
  tasks:
    - name: Show ps
      shell: ps aux | grep -E "^{{ kyoushi_user_name[:7] }}"
      register: out
      become: yes
    - debug:
        var: out
    - name: Kill SM
      shell: kill $(ps aux | grep -E "^{{ kyoushi_user_name[:7] }}" | tr -s ' ' | cut -d" " -f2)
      args:
        executable: /bin/bash
      become: yes
    